### ISSUE TITLE
Compile error, at SigmoidCrossEntropyLoss Layer

### ISSUE THREAD

**Issue by izzymat1102** [s9xie/hed#10]
Hi, under Ubuntu 14.04, CPU mode, I tried to run hed but got an error that says following:

CXX src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp:118:1: error: no ‘void caffe::SigmoidCrossEntropyLossLayer<Dtype>::Backward_gpu(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<bool>&, const std::vector<caffe::Blob<Dtype>*>&)’ member function declared in class ‘caffe::SigmoidCrossEntropyLossLayer<Dtype>’
make: *** [.build_release/src/caffe/layers/sigmoid_cross_entropy_loss_layer.o] Error 1

I read "sigmoid_cross_entropy_loss_layer.cpp" and 
it seems that "sigmoid_cross_entropy_loss_layer.hpp" file, which declare the class SigmoidCrossEntropyLossLayer<Dtype>::Backward_gpu
is deleted in this hed version, and instead includes "caffe/layer.hpp" file
that the class but not in the name of SigmoidCross...

Does anyone have the same issue and solved? I look forward to your reply or any suggestions, thanks!

**Comment by s9xie** [comment]
Please use the modified-caffe version in this github repo. The error is due to changes in the header files (gpu implementation was removed).
