### ISSUE TITLE
caffe crash when I set batch size > 1

### ISSUE THREAD

**Issue by weiliu620** [s9xie/hed#17]
When I use default batch_size  = 1, run 'caffe train --solver solver.prototxt' works. But if I set batch_size = 2 in train_val file, caffe crashes. 
=============== error log ==============
...
layer {
  type: "SigmoidCrossEntropyLoss"
  bottom: "upscore-fuse"
  bottom: "label"
  top: "fuse_loss"
  loss_weight: 1
}
    @     0x7f5207b74a4a  (unknown)
I0509 14:28:30.309254 22135 layer_factory.hpp:76] Creating layer data
I0509 14:28:30.309273 22135 net.cpp:111] Creating Layer data
I0509 14:28:30.309281 22135 net.cpp:434] data -> data
I0509 14:28:30.309293 22135 net.cpp:434] data -> label
I0509 14:28:30.309303 22135 image_labelmap_data_layer.cpp:40] Opening file ../../data/HED-BSDS/train_pair.lst
    @     0x7f5207953182  start_thread
    @     0x7f520807d47d  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)
============= end of errors =====================

Sometimes I got this error: 
============== error log ===============
layer {
  type: "SigmoidCrossEntropyLoss"
  bottom: "upscore-fuse"
  bottom: "label"
  top: "fuse_loss"
  loss_weight: 1
}
    @     0x7fe89b337598  caffe::ImageLabelmapDataLayer<>::load_batch()
I0509 14:34:30.756006 24849 layer_factory.hpp:76] Creating layer data
I0509 14:34:30.756026 24849 net.cpp:111] Creating Layer data
I0509 14:34:30.756033 24849 net.cpp:434] data -> data
I0509 14:34:30.756044 24849 net.cpp:434] data -> label
I0509 14:34:30.756054 24849 image_labelmap_data_layer.cpp:40] Opening file ../../data/HED-BSDS/train_pair.lst
    @     0x7fe89b2aeda9  caffe::BasePrefetchingLabelmapDataLayer<>::InternalThreadEntry()
    @     0x7fe89b24bb6f  caffe::InternalThread::entry()
    @     0x7fe89958fa4a  (unknown)
    @     0x7fe89936e182  start_thread
    @     0x7fe899a9847d  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)
================ end of errors ==============

When the batch size has to be one? And I think my card has large enough memory for > 2 images as input...

**Comment by zeakey** [comment]
@weiliu620 images in bsds has variant sizes, so batch can be 1 only
