### ISSUE TITLE
Training on NYUD dataset

### ISSUE THREAD

**Issue by Fengyboy** [s9xie/hed#2]
Hi Saining,

I would like to reproduce the results of NYUD dataset in your paper. Could you please provide details on how to prepare the dataset in an acceptable format to the HED algorithm? For example, do I need to argument the images in a similar manner as the BSD dataset? How to convert a binary boundary mask to the ground truth format?

Looking forward to your reply and many thanks,
Feng

**Comment by athiselvam** [comment]
Hi @Fengyboy ,

Did you find the way to train HED with NYUD?

If you did please share the method to do that?
