### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by yexiguafuqihao** [s9xie/hed#3]
It is nice to read your innovative paper and I want to replicate your performance you posted on your thesie ,Unfortunately,there were some error happens when I compile your lastest project. would your please to fix these bugs.

**Comment by s9xie** [comment]
@yexiguafuqihao Hi, can you post the specific error you encountered? The code has been tested on Ubuntu 14.04.

**Comment by yexiguafuqihao** [comment]
@s9xie src/caffe/data_transformer.cpp:319:  Should have a space between // and comment  [whitespace/comments] [4]
src/caffe/data_transformer.cpp:322:  Lines should very rarely be longer than 100 characters  [whitespace/line_length] [4]
src/caffe/data_transformer.cpp:322:  Is this a non-const reference? If so, make const or use a pointer: int &h_off  [runtime/references] [2]
src/caffe/data_transformer.cpp:322:  Is this a non-const reference? If so, make const or use a pointer: int &w_off  [runtime/references] [2]
src/caffe/data_transformer.cpp:322:  Is this a non-const reference? If so, make const or use a pointer: bool &do_mirror  [runtime/references] [2]
src/caffe/data_transformer.cpp:413:  Redundant blank line at the end of a code block should be deleted.  [whitespace/blank_line] [3]
src/caffe/data_transformer.cpp:415:  Should have a space between // and comment  [whitespace/comments] [4]
src/caffe/data_transformer.cpp:419:  Lines should very rarely be longer than 100 characters  [whitespace/line_length] [4]
src/caffe/data_transformer.cpp:437:  Should have a space between // and comment  [whitespace/comments] [4]
src/caffe/data_transformer.cpp:445:  Line ends in whitespace.  Consider deleting these extra spaces.  [whitespace/end_of_line] [4]
src/caffe/data_transformer.cpp:472:  Should have a space between // and comment  [whitespace/comments] [4]
Total errors found: 11
src/caffe/layers/base_data_layer.cu:32:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
Total errors found: 1
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp:38:  Should have a space between // and comment  [whitespace/comments] [4]
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp:56:  Tab found; better to use spaces  [whitespace/tab] [1]
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp:56:  Extra space for operator  ++;  [whitespace/operators] [4]
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp:57:  Tab found; better to use spaces  [whitespace/tab] [1]
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp:57:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp:58:  Tab found; better to use spaces  [whitespace/tab] [1]
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp:58:  Lines should very rarely be longer than 100 characters  [whitespace/line_length] [4]
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp:59:  Tab found; better to use spaces  [whitespace/tab] [1]
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp:60:  Tab found; better to use spaces  [whitespace/tab] [1]
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp:60:  An else should appear on the same line as the preceding }  [whitespace/newline] [4]
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp:61:  Tab found; better to use spaces  [whitespace/tab] [1]
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp:61:  Extra space for operator  ++;  [whitespace/operators] [4]
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp:62:  Tab found; better to use spaces  [whitespace/tab] [1]
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp:62:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp:63:  Tab found; better to use spaces  [whitespace/tab] [1]
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp:63:  Lines should very rarely be longer than 100 characters  [whitespace/line_length] [4]
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp:64:  Tab found; better to use spaces  [whitespace/tab] [1]
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp:65:  Line ends in whitespace.  Consider deleting these extra spaces.  [whitespace/end_of_line] [4]
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp:93:  Tab found; better to use spaces  [whitespace/tab] [1]
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp:94:  Tab found; better to use spaces  [whitespace/tab] [1]
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp:95:  Tab found; better to use spaces  [whitespace/tab] [1]
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp:96:  Tab found; better to use spaces  [whitespace/tab] [1]
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp:97:  Tab found; better to use spaces  [whitespace/tab] [1]
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp:97:  Extra space for operator  ++;  [whitespace/operators] [4]
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp:98:  Tab found; better to use spaces  [whitespace/tab] [1]
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp:99:  Tab found; better to use spaces  [whitespace/tab] [1]
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp:99:  An else should appear on the same line as the preceding }  [whitespace/newline] [4]
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp:100:  Tab found; better to use spaces  [whitespace/tab] [1]
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp:100:  Extra space for operator  ++;  [whitespace/operators] [4]
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp:101:  Tab found; better to use spaces  [whitespace/tab] [1]
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp:102:  Tab found; better to use spaces  [whitespace/tab] [1]
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp:103:  Tab found; better to use spaces  [whitespace/tab] [1]
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp:104:  Tab found; better to use spaces  [whitespace/tab] [1]
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp:105:  Tab found; better to use spaces  [whitespace/tab] [1]
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp:105:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp:106:  Tab found; better to use spaces  [whitespace/tab] [1]
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp:107:  Tab found; better to use spaces  [whitespace/tab] [1]
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp:107:  An else should appear on the same line as the preceding }  [whitespace/newline] [4]
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp:108:  Tab found; better to use spaces  [whitespace/tab] [1]
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp:108:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp:109:  Tab found; better to use spaces  [whitespace/tab] [1]
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp:110:  Tab found; better to use spaces  [whitespace/tab] [1]
src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp:112:  Extra space before [  [whitespace/braces] [5]
Total errors found: 43
src/caffe/layers/base_conv_layer.cpp:11:  Line ends in whitespace.  Consider deleting these extra spaces.  [whitespace/end_of_line] [4]
src/caffe/layers/base_conv_layer.cpp:12:  Line ends in whitespace.  Consider deleting these extra spaces.  [whitespace/end_of_line] [4]
Total errors found: 2
src/caffe/layers/base_data_layer.cpp:195:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
Total errors found: 1
src/caffe/layers/image_labelmap_data_layer.cpp:11:  Include "cstdlib" not in alphabetical order  [build/include_alpha] [4]
src/caffe/layers/image_labelmap_data_layer.cpp:28:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/caffe/layers/image_labelmap_data_layer.cpp:28:  Except the base classes, Caffe DataLayer should define DataLayerSetUp instead of LayerSetUp. The base DataLayers define common SetUp steps, the subclasses should not override them.  [caffe/data_layer_setup] [2]
src/caffe/layers/image_labelmap_data_layer.cpp:73:  Line ends in whitespace.  Consider deleting these extra spaces.  [whitespace/end_of_line] [4]
src/caffe/layers/image_labelmap_data_layer.cpp:73:  Should have a space between // and comment  [whitespace/comments] [4]
src/caffe/layers/image_labelmap_data_layer.cpp:74:  Line ends in whitespace.  Consider deleting these extra spaces.  [whitespace/end_of_line] [4]
src/caffe/layers/image_labelmap_data_layer.cpp:75:  Line ends in whitespace.  Consider deleting these extra spaces.  [whitespace/end_of_line] [4]
src/caffe/layers/image_labelmap_data_layer.cpp:76:  Line ends in whitespace.  Consider deleting these extra spaces.  [whitespace/end_of_line] [4]
src/caffe/layers/image_labelmap_data_layer.cpp:77:  Line ends in whitespace.  Consider deleting these extra spaces.  [whitespace/end_of_line] [4]
src/caffe/layers/image_labelmap_data_layer.cpp:78:  Line ends in whitespace.  Consider deleting these extra spaces.  [whitespace/end_of_line] [4]
src/caffe/layers/image_labelmap_data_layer.cpp:79:  Line ends in whitespace.  Consider deleting these extra spaces.  [whitespace/end_of_line] [4]
src/caffe/layers/image_labelmap_data_layer.cpp:80:  Line ends in whitespace.  Consider deleting these extra spaces.  [whitespace/end_of_line] [4]
src/caffe/layers/image_labelmap_data_layer.cpp:81:  Line ends in whitespace.  Consider deleting these extra spaces.  [whitespace/end_of_line] [4]
src/caffe/layers/image_labelmap_data_layer.cpp:81:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/caffe/layers/image_labelmap_data_layer.cpp:82:  Consider using CHECK_EQ instead of CHECK(a == b)  [readability/check] [2]
src/caffe/layers/image_labelmap_data_layer.cpp:83:  Line ends in whitespace.  Consider deleting these extra spaces.  [whitespace/end_of_line] [4]
src/caffe/layers/image_labelmap_data_layer.cpp:85:  Line ends in whitespace.  Consider deleting these extra spaces.  [whitespace/end_of_line] [4]
src/caffe/layers/image_labelmap_data_layer.cpp:93:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/caffe/layers/image_labelmap_data_layer.cpp:94:  Line ends in whitespace.  Consider deleting these extra spaces.  [whitespace/end_of_line] [4]
src/caffe/layers/image_labelmap_data_layer.cpp:152:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/caffe/layers/image_labelmap_data_layer.cpp:153:  Line ends in whitespace.  Consider deleting these extra spaces.  [whitespace/end_of_line] [4]
src/caffe/layers/image_labelmap_data_layer.cpp:159:  Line ends in whitespace.  Consider deleting these extra spaces.  [whitespace/end_of_line] [4]
src/caffe/layers/image_labelmap_data_layer.cpp:185:  Lines should very rarely be longer than 100 characters  [whitespace/line_length] [4]
src/caffe/layers/image_labelmap_data_layer.cpp:186:  Consider using CHECK_EQ instead of CHECK(a == b)  [readability/check] [2]
src/caffe/layers/image_labelmap_data_layer.cpp:187:  Line ends in whitespace.  Consider deleting these extra spaces.  [whitespace/end_of_line] [4]
src/caffe/layers/image_labelmap_data_layer.cpp:190:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/caffe/layers/image_labelmap_data_layer.cpp:203:  Should have a space between // and comment  [whitespace/comments] [4]
src/caffe/layers/image_labelmap_data_layer.cpp:209:  Lines should very rarely be longer than 100 characters  [whitespace/line_length] [4]
src/caffe/layers/image_labelmap_data_layer.cpp:210:  Line ends in whitespace.  Consider deleting these extra spaces.  [whitespace/end_of_line] [4]
src/caffe/layers/image_labelmap_data_layer.cpp:212:  Should have a space between // and comment  [whitespace/comments] [4]
src/caffe/layers/image_labelmap_data_layer.cpp:214:  Should have a space between // and comment  [whitespace/comments] [4]
src/caffe/layers/image_labelmap_data_layer.cpp:215:  Lines should very rarely be longer than 100 characters  [whitespace/line_length] [4]
src/caffe/layers/image_labelmap_data_layer.cpp:215:  Should have a space between // and comment  [whitespace/comments] [4]
src/caffe/layers/image_labelmap_data_layer.cpp:216:  Should have a space between // and comment  [whitespace/comments] [4]
src/caffe/layers/image_labelmap_data_layer.cpp:217:  Lines should very rarely be longer than 100 characters  [whitespace/line_length] [4]
src/caffe/layers/image_labelmap_data_layer.cpp:217:  Should have a space between // and comment  [whitespace/comments] [4]
src/caffe/layers/image_labelmap_data_layer.cpp:219:  Lines should very rarely be longer than 100 characters  [whitespace/line_length] [4]
src/caffe/layers/image_labelmap_data_layer.cpp:220:  Line ends in whitespace.  Consider deleting these extra spaces.  [whitespace/end_of_line] [4]
Total errors found: 38
include/caffe/data_layers.hpp:313:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
include/caffe/data_layers.hpp:313:  At least two spaces is best between code and comments  [whitespace/comments] [2]
include/caffe/data_layers.hpp:313:  Should have a space between // and comment  [whitespace/comments] [4]
Total errors found: 3
include/caffe/data_transformer.hpp:90:  Line ends in whitespace.  Consider deleting these extra spaces.  [whitespace/end_of_line] [4]
include/caffe/data_transformer.hpp:91:  Should have a space between // and comment  [whitespace/comments] [4]
include/caffe/data_transformer.hpp:92:  Lines should very rarely be longer than 100 characters  [whitespace/line_length] [4]
include/caffe/data_transformer.hpp:93:  Should have a space between // and comment  [whitespace/comments] [4]
include/caffe/data_transformer.hpp:95:  Should have a space between // and comment  [whitespace/comments] [4]
include/caffe/data_transformer.hpp:96:  Lines should very rarely be longer than 100 characters  [whitespace/line_length] [4]
include/caffe/data_transformer.hpp:96:  Is this a non-const reference? If so, make const or use a pointer: int &h_off  [runtime/references] [2]
include/caffe/data_transformer.hpp:96:  Is this a non-const reference? If so, make const or use a pointer: int &w_off  [runtime/references] [2]
include/caffe/data_transformer.hpp:96:  Is this a non-const reference? If so, make const or use a pointer: bool &do_mirror  [runtime/references] [2]
include/caffe/data_transformer.hpp:97:  Should have a space between // and comment  [whitespace/comments] [4]
Total errors found: 10
include/caffe/loss_layers.hpp:647:  Should have a space between // and comment  [whitespace/comments] [4]
Total errors found: 1

**Comment by yexiguafuqihao** [comment]
and my OS is Ubuntu14.04 just like yours.

**Comment by yexiguafuqihao** [comment]
Thanks for your answer and I have solved my compilation problem.
