### ISSUE TITLE
An error occurred using cuda make

### ISSUE THREAD

**Issue by wulivicte** [s9xie/hed#34]
When I use cuda8.0 version of the compiler, have an error:/hed-master/include/caffe/util/cudnn.hpp(123): error: argument of type "int" is incompatible with parameter of type "cudnnNanPropagation_t"
Is it a version issue?What cuda version should I use?

There are other errors using cuda7.5 :
`make[2]: *** [src/caffe/CMakeFiles/cuda_compile.dir/util/./cuda_compile_generated_im2col.cu.o] Error 1
make[2]: *** [src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_base_data_layer.cu.o] Error 1
make[2]: CMake Error at cuda_compile_generated_cudnn_softmax_layer.cu.o.cmake:208 (message):
  Error generating
  /opt/yangmiao/hed-master/src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_cudnn_softmax_layer.cu.o
CMake Error at cuda_compile_generated_silence_layer.cu.o.cmake:208 (message):
  Error generating
  /opt/yangmiao/hed-master/src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_silence_layer.cu.o

`what should I do？

**Comment by hellodrx** [comment]
My experience is to use CUDA 7.0 + CUDNN 3.0 to compile this version of caffe. It works very well for me.

**Comment by wulivicte** [comment]
thanks
