### ISSUE TITLE
http request error

### ISSUE THREAD

**Issue by kemangjaka** [s9xie/hed#74]
Hi, thanks for providing the code!
When I tried to download HED-BSDS.tar, I cannot connect to the server. 
(http://vcl.ucsd.edu/hed/HED-BSDS.tar)

How do I download the data? Or how did you modify the original dataset?

Thank you!

**Comment by xwjabc** [comment]
The link is fixed now.

**Comment by kemangjaka** [comment]
thank you for the response.
