### ISSUE TITLE
Compilation Error during runtest

### ISSUE THREAD

**Issue by mahaling** [s9xie/hed#9]
Hello All,

I am trying to compile the version of caffe included and I am getting the following error during runtest 
My traditional version of caffe and other versions compile without any issues. 
It would be great id somebody can shed some light on this. 
I am compiling with cuda and cudnn along WITH_PYTHON_LAYER = 1

[  FAILED  ] 8 tests, listed below:
[  FAILED  ] SigmoidCrossEntropyLossLayerTest/0.TestSigmoidCrossEntropyLoss, where TypeParam = caffe::CPUDevice<float>
[  FAILED  ] SigmoidCrossEntropyLossLayerTest/0.TestGradient, where TypeParam = caffe::CPUDevice<float>
[  FAILED  ] SigmoidCrossEntropyLossLayerTest/1.TestGradient, where TypeParam = caffe::CPUDevice<double>
[  FAILED  ] SigmoidCrossEntropyLossLayerTest/1.TestSigmoidCrossEntropyLoss, where TypeParam = caffe::CPUDevice<double>
[  FAILED  ] SigmoidCrossEntropyLossLayerTest/2.TestSigmoidCrossEntropyLoss, where TypeParam = caffe::GPUDevice<float>
[  FAILED  ] SigmoidCrossEntropyLossLayerTest/2.TestGradient, where TypeParam = caffe::GPUDevice<float>
[  FAILED  ] SigmoidCrossEntropyLossLayerTest/3.TestGradient, where TypeParam = caffe::GPUDevice<double>
[  FAILED  ] SigmoidCrossEntropyLossLayerTest/3.TestSigmoidCrossEntropyLoss, where TypeParam = caffe::GPUDevice<double>

 8 FAILED TESTS
  YOU HAVE 2 DISABLED TESTS

F0218 20:59:02.200268 12246 syncedmem.hpp:30] Check failed: error == cudaSuccess (29 vs. 0)  driver shutting down
*** Check failure stack trace: ***
    @     0x2b451c9addaa  (unknown)
    @     0x2b451c9adce4  (unknown)
    @     0x2b451c9ad6e6  (unknown)
    @     0x2b451c9b0687  (unknown)
    @     0x2b451d7f32ff  caffe::SyncedMemory::~SyncedMemory()
    @           0x464f52  boost::detail::sp_counted_impl_p<>::dispose()
    @           0x45779e  boost::detail::sp_counted_base::release()
    @     0x2b451e56c5ea  (unknown)
    @     0x2b451d772d73  (unknown)
make: *** [runtest] Aborted (core dumped)

**Comment by s9xie** [comment]
GPU implementation is not included in this version of caffe, thus runtest failed. You can ignore the runtest error.

**Comment by appyfizzA** [comment]
I am getting this same error. If this version does not support GPU, then I am surprised how training occured in GPU? 

I trained the M2FCN network which is based on HED, and while testing I am trying to run "make runtest $nproc", and I am getting the same error trace as posted here.
